---
title: "Cartography"
author: "Pablo Gomez"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr); library(ggplot2); library(ggpubr);library(Pabloverse); library(sf)
```

Ok now that we are familiarized with spatial data and visualization, we can go more detailed into making a pretty map.

```{r}
capturaSp
```


# Extent

```{r}
bbox <- st_bbox(capturaSp)

ggplot() +
  geom_sf(data = Area,col = 'grey60') +
  geom_sf(data = capturaSp, cex = 0.6) +
  theme_void() +
  scale_fill_gradient(low = 'black', high = 'red') +
  lims(x = bbox[c(1, 3)], y = bbox[c(2, 4)]) 
```

# Scale bar

```{r}
bbox <- st_bbox(capturaSp)

ggplot() +
  geom_sf(data = Area,col = 'grey60') +
  geom_sf(data = capturaSp, cex = 0.6) +
  theme_void() +
  scale_fill_gradient(low = 'black', high = 'red') +
  lims(x = bbox[c(1, 3)], y = bbox[c(2, 4)]) +
  annotation_scale(location = 'br', width_hint = 0.25, line_width = 0.2, height = unit(.03, "in")) 
```

# Facets

```{r}
ggplot(data = capturaSp) +
  geom_sf(data = Area,col = 'grey60') +
  geom_sf(cex = 0.6) +
  theme_void() +
  scale_fill_gradient(low = 'black', high = 'red') +
  lims(x = bbox[c(1, 3)], y = bbox[c(2, 4)]) +
  facet_wrap(~YEAR)
```


# Legends

# Facets

# Names

```{r}
library(ggspatial)

ggplot() +
  geom_sf(data = Area,col = 'grey60') +
  # geom_sf_text(data = Area, aes(label = NOMGEO), alpha = 0.6, col = 'grey90') +
  geom_sf(data = capturaSp, cex = 0.3) +
  theme_void() +
  scale_fill_gradient(low = 'black', high = 'red') +
  annotation_scale(location = 'br', width_hint = 0.25, line_width = 0.2, height = unit(.03, "in")) +
  annotation_north_arrow(location = "tr", which_north = "true", style = north_arrow_fancy_orienteering(text_size = 5), 
                         height = unit(.6, "in"),
                         width = unit(.6, "in"),
                         pad_x = unit(0.05, "in"), pad_y = unit(0.05, "in"))
```

# 
